### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Thedragoni1** [DragN0007/Overhauled-Livestock#1]
From what i've noticed for alot of animals (especially the bigger one's) the animations either dont play or dont stop playing, for example the pig is constantly walking even when its stopped, the horses dont walk- almost ever same with the cows and im guessing the horse is supposed to have some form of an attacking animation..? Im guessing atleast since when i accidently punched a horse (i assume) it started to attack me but it was in a constant t-pose

Havent noticed any animation issues with the chickens nor sheep

**Comment by DragN0007** [comment]
This is actually all a Geckolib issue. If you have shaders or any sort of shader loader, like Optifine or Iris, you need to turn off your Entity Shadows in your game options *and* your shader options ^^

We can't actually fix this issue on our end. Geckolib has yet to fix it.

**Comment by Thedragoni1** [comment]
> This is actually all a Geckolib issue. If you have shaders or any sort of shader loader, like Optifine or Iris, you need to turn off your Entity Shadows in your game options _and_ your shader options ^^
> 
> I've also noticed that Oculus is the worst about the animation issues. I would suggest using Optifine instead if you have it.
> 
> We can't actually fix this issue on our end. Geckolib has yet to fix it.

**Comment by Thedragoni1** [comment]
OHHHH MY BAD MY BAD i didnt knew that lol ty for the info :D

I am using optifine so its probably the shaders themselves flippin the lid, sorry for that <:D

(also dont mind my previous reply, im new to commenting on github and im messing everything up lol)

**Comment by DragN0007** [comment]
No worries, happy to help 😄 Have fun!
