### ISSUE TITLE
O-Cows being weird?

### ISSUE THREAD

**Issue by TheMagpieKin** [DragN0007/Overhauled-Livestock#11]
**Bug Description:**
Unsure if it's a bug, but I've noticed that some of my cows will attempt to herd together but end up in this massive clump, where one (I assume the one the AI decided is leading the herd) ends up in the middle, with the rest basically trying to follow it surrounding it. I've tried using a horse to scare them away from each other and they'll flee just fine, but once they're far enough from the horse they clump up again. The rest of my cows will herd in groups of 2-4 and don't have this issue. They have a very large enclosure so space isn't the issue. They'll do this even if they're the only cows in the pen, and they'll follow wheat but always end up back in a clump, and usually end up at a fence as they push each other around.

**Mod Version:**
1.4 (Though was happening to me on earlier versions, 1.3)
**Minecraft Version:**
1.20.1
**Screenshot (Optional):**
![2024-11-21_17 31 03](https://github.com/user-attachments/assets/efaab165-59ca-46b4-97f8-6a62a15f920e)

**Have you tried removing other mods? Did the issue persist after removing them?:**
Don't believe other mods are the issue
**Are you on Singleplayer or a Server?:**
Singleplayer

**Comment by TheMagpieKin** [comment]
![2024-11-21_17 39 30](https://github.com/user-attachments/assets/0214668d-e3e5-46f5-9639-c619a58d578f)
![2024-11-21_17 39 10](https://github.com/user-attachments/assets/7159a801-18dc-475f-b0ef-6b04bb2a384a)
![2024-11-21_17 39 21](https://github.com/user-attachments/assets/c888a535-88bb-4170-8d75-2282145a1f4b)
Think this is an issue when 5+ cows begin to herd together? My herd of 4 cows were pushing it but they were walking just fine

**Comment by DragN0007** [comment]
This is just an unfortunate consequence of the cow herding mechanic. 

I can only suggest maybe keeping 4 cows in the same pen at once, or just letting them do their favorite thing and push the leader around. If you want, I can see if I can add a config to be able to turn off animals herding together.

**Comment by TheMagpieKin** [comment]
As long as it isn't a glitch, I'm not worried. A config to turn it off might be nice for those who have more cows then me or want them for aesthetic reasons
