### ISSUE TITLE
Crash Report: mokiyoki/enhancedanimals/entity/EnhancedRabbit, when opening worlds

### ISSUE THREAD

**Issue by Clhunt23** [DragN0007/Overhauled-Livestock#13]

**Comment by DragN0007** [comment]
This is not my mod. 😬

**Comment by Clhunt23** [comment]
> This is not for my mod. 😬 That crash isn't for Livestock Overhaul.

So sorry!! Tried to fix it and looks like its a Genetic Animals mod but I don't have it anymore, so I'm gonna try and redownload minecraft as a whole.  Sorry for the trouble!! I've gotten the mod to work a few times and its lovely so far, really appreciate the work and energy you have put into it!

**Comment by DragN0007** [comment]
No worries. Maybe some files got left behind by GA or something?

**Comment by Clhunt23** [comment]
Maybe!! I'll let you know how it goes.

**Comment by Clhunt23** [comment]
> No worries. Maybe some files got left behind by GA or something?

I had to delete everything related to Minecraft from my computer because the file was just hiding somewhere, but after redownloading everything and not using GA, it works!!
