### ISSUE TITLE
Rabbits only breeding females

### ISSUE THREAD

**Issue by TheMagpieKin** [DragN0007/Overhauled-Livestock#15]
**Bug Description:**
As the title says, when I breed the O-rabbits together, they only produce female babies. I'll still find males in the wild and through spawn eggs, but I cannot breed any males.

**Mod Version:**

**Minecraft Version:** 1.20.1

**Screenshot (Optional):**

**Have you tried removing other mods? Did the issue persist after removing them?:** I don't have any animal breeding mods so I don't believe those would be a cause.

**Are you on Singleplayer or a Server?:** Server (though I tested in a creative singleplayer and this was still happening)

**Comment by DragN0007** [comment]
I'll fix this up for next update ^-^

**Comment by TheMagpieKin** [comment]
Amazing, thank you!
