### ISSUE TITLE
Beehive Spawned over 2,000 Bees

### ISSUE THREAD

**Issue by 1bekind1** [DragN0007/Overhauled-Livestock#17]
**Bug Description: A newly formed beehive spawned over 2,000 O-Bees - I was wondering what was causing so much lag in my game and suddenly there were a TON of bees**

**Mod Version: 1.5**

**Minecraft Version: 1.20.1**

**Screenshot (Optional):
![2024-12-03_13 30 27](https://github.com/user-attachments/assets/d964f466-dc65-49d6-ad05-ee8c9dd0dab6)
![2024-12-03_13 30 31](https://github.com/user-attachments/assets/24ba8bd6-3d4a-4dbf-9d2c-708483647183)
![2024-12-03_13 31 20](https://github.com/user-attachments/assets/8bd9c7f3-e260-4080-9dc0-dcc115528198)**

**Have you tried removing other mods? Did the issue persist after removing them?: No, I have not tried removing any mods**
[Modpack.zip](https://github.com/user-attachments/files/17997996/Modpack.zip)
This is the modpack I was playing with, it is custom.

**Are you on Singleplayer or a Server?: Singleplayer**

**Comment by DragN0007** [comment]
Remove mods, try with just Livestock Overhaul and Geckolib and report back.
