### ISSUE TITLE
Unable to convert wool to string 

### ISSUE THREAD

**Issue by FatherPigeon** [DragN0007/Overhauled-Livestock#19]
**Bug Description: There's a crafting recipe to convert wool into string, I'm not too sure what causes this but for some reason I added the mod and I thin kafter the 1.4 update I just haven't been able to convert to string? **

**Mod Version: currently on version 1.6 but it's been an issue since 1.4**

**Minecraft Version: 1.20.1**

**Screenshot (Optional):**

**Have you tried removing other mods? Did the issue persist after removing them?: Yes, and yes. It seems it may be something with the tags **

**Are you on Singleplayer or a Server?: Singleplayer**

**Comment by DragN0007** [comment]
This recipe is from an entirely different mod. Livestock Overhaul doesn't do wool > string conversions. O-Sheep drop vanilla wool as well
