### ISSUE TITLE
Horse Inventory can be overfilled to cause game crash

### ISSUE THREAD

**Issue by LilcatSilly** [DragN0007/Overhauled-Livestock#20]
**Bug Description:**
Game crashes after putting more than 9 items in horse inventory.
When shift right click a horse(that has saddlebags) while dismounted you see the 3x3 item grid (9 slots)
But while mounted and opening your inventory (Pressing E by default) you see 5x3 (15 slots). Trying to full all the slots, or over 9 of them, causes a game crash with the error code " -1 "
**Mod Version:**
1.5 (I first found it here) and 1.6 (newest version still has it)
**Minecraft Version:**
1.20.1
**Screenshot (Optional):**
![2024-12-07_19 15 30](https://github.com/user-attachments/assets/75001bdd-5667-4b1f-9e70-a2d2f1568155)
![2024-12-07_19 15 37](https://github.com/user-attachments/assets/19752135-bf82-48df-a7f2-75f38853fa1a)
**Have you tried removing other mods? Did the issue persist after removing them?:**
Yes. Tested with only Livestock mod and still got the same results.
**Are you on Singleplayer or a Server?:**
Both have been tested and still crashes

**Comment by DragN0007** [comment]
Was this horse spawned in before 1.5 or 1.6 by chance, or is it newly-spawned after updating?

If it's an older horse, try shearing off the chests and putting them back on. 
Otherwise, just let me know and I'll take a look

**Comment by LilcatSilly** [comment]
No in both versions the horses where originally from that version to start. I did try for the sake of trying shearing the chest off a horse in the 1.6 version and after reputing it on I was still able to crash the game with the same actions.

**Comment by DragN0007** [comment]
Ah okay, thanks for trying anyway.

I'll take a look

**Comment by DragN0007** [comment]
Wait, what's up with your breed text? LOL

I'll take a look at that too while I'm at I suppose

**Comment by LilcatSilly** [comment]
LOL it's been like that for me even in 1.5 (the version i first started playing of the mod) so i thought it was normal XD

**Comment by Thats-MyLive** [comment]
Made me curious and I went to testing cause i havent had a chest on any of my horses yet. I started a new game with the latest update and have some horses there, so they are not from 1.5 or before.
When riding the inventory is 15 slots, when i open the inventory with shift-click from the ground it has only 9 slots. I cannot make my game crash with overfilling it tho. Its just as if it is cut-off in the interface, but i cannot access the items in the last 6 slots unless opening the inventory while riding.

**Comment by LilcatSilly** [comment]
Yes the only time I am able to overfill the horses inventory slots to make
the crash happen is while riding the horse (seeing the 15 slot inventory).
Have you tired manually(clicking and draging the item into the slot)
putting more than 9 in this menu? If you only shift click the items from
your inventory to the horses inventory it will not trigger the bug. (I can
provide video shortly of what I mean too)

**Comment by LilcatSilly** [comment]
Heres the video. I try shift clicking items in until they stop doing into the horses inventory. Then I click and drag a item (note the horse already has 9 items so im adding a 10th) into a open slot, at which the game crashes (video ends because of this)

https://github.com/user-attachments/assets/865d3e38-6a07-42a3-b0df-231df821dc81

**Comment by LilcatSilly** [comment]
(i forgot i was going to add this also for the sakes of extra infos)
Pictures showing in detail what versions I am using in the video (tho as i mentioned I have found it in other versions/settings)
![image](https://github.com/user-attachments/assets/42d9c571-74bc-4a39-9f2a-d32b3bb39163)
![image](https://github.com/user-attachments/assets/3587c798-aff0-448d-a122-d5fae1f9ad33)

**Comment by Thats-MyLive** [comment]
Yeah okay, with trying to drag an item in I can get mine to crash as well. I usually only shift click. Interestingly enough tho mine fills the 15 slot inventory with shift click up. Only the dragging doesnt seem to work for me on those slots.

**Comment by DragN0007** [comment]
I know what the issue is caused by and will be attempting to fix it soon, please be patient with me!

**Comment by LilcatSilly** [comment]
No worries and no rush! Happy to helps!
