### ISSUE TITLE
Shire layer conflicting with Roan/Socks texture

### ISSUE THREAD

**Issue by Canidjourney** [DragN0007/Overhauled-Livestock#23]
**Bug Description: bred a shire horse with a fjord that had roan came out with a shire with the roan which had weird flicking texture each time you look at it at an angle**

**Mod Version:1.20.1 - 1.7**

**Minecraft Version:1.20.1**

**Screenshot (Optional):** 

**Have you tried removing other mods? Did the issue persist after removing them?: It is the only serversided mod as I was comparing horse mods**

**Are you on Singleplayer or a Server?: Singleplayer**

https://github.com/user-attachments/assets/b0bceee3-4492-4b95-8976-88dc40b17713

**Comment by DragN0007** [comment]
This probably isn't a livestock overhaul issue. You can try:

-Downgrading your Geckolib version to something like 1.20.1-4.4.4

-Using Optifine instead of Iris/ Oculus (if applicable)
