### ISSUE TITLE
horses

### ISSUE THREAD

**Issue by bonbon20110** [DragN0007/Overhauled-Livestock#26]
**Bug Description:**
I do not know if the creators will divot time to solve this issue but with swem instilled I cannot convert an o horse to a swem horse 
 thank you

**Mod Version:**1.20.1-1.3.jar

**Minecraft Version:**1.20.1

**Screenshot (Optional):**

**Have you tried removing other mods? Did the issue persist after removing them?:**the issue is with a mod that your suppose to be compatible with

**Are you on Singleplayer or a Server?:** singleplayer

**Comment by DragN0007** [comment]
Update to 1.20.1-1.7, this compatibility feature has been in the mod for a while.
