### ISSUE TITLE
Nether Spawns.

### ISSUE THREAD

**Issue by TheLadyToasty** [DragN0007/Overhauled-Livestock#27]
**Bug Description: I was watching one of my player's screenshare and they were in the nether. a TON of horses spawned right in front of them and then crashed the server due to overloaded chunks.**

**Mod Version: 1.20.1-1.6. Unsure if its already fixed.**

**Minecraft Version: 1.20.1**

**Have you tried removing other mods? Did the issue persist after removing them?: We have and no luck so far**

**Are you on Singleplayer or a Server?: Server**

-Before posting an issue, please make sure you’re on the latest version of the mod. There’s a possibility it’s already been fixed!

**Comment by DragN0007** [comment]
Remove Mystic Mounts or turn off O-Horse spawning

**Comment by DragN0007** [comment]
Now fixed in 1.20.1-2.1! No ETA on release
