### ISSUE TITLE
Chickens spawning in the ocean?

### ISSUE THREAD

**Issue by crystal1212-star** [DragN0007/Overhauled-Livestock#29]
**Bug Description:**
I’m in a survival world of a modpack I made which includes this mod and o-chickens keep spawning in the middle of the ocean- any idea why this may be happening and how to fix it?

**Mod Version:** 
1.7

**Minecraft Version:**
1.20.1

**Screenshot (Optional):**

**Have you tried removing other mods? Did the issue persist after removing them?:**
Have not tried

**Are you on Singleplayer or a Server?:** singleplayer

-Before posting an issue, please make sure you’re on the latest version of the mod. There’s a possibility it’s already been fixed!

**Comment by DragN0007** [comment]
This isn't an LO issue. LO doesn't have its own spawning, the animals simply replace vanilla ones that are already spawning/ spawned in the world 

Try removing other mods. One is probably causing weird animal spawns.

**Comment by crystal1212-star** [comment]
Hm, alright well thank you for the fast response. I’ll see if i can figure out what mod is causinf it
