### ISSUE TITLE
O-horses spawn with bridle

### ISSUE THREAD

**Issue by Rinkavlu** [DragN0007/Overhauled-Livestock#3]
Happens with donkeys, mules and unicorns
![image_2024-11-12_101830178](https://github.com/user-attachments/assets/0d71e527-0f1a-4d9b-b79f-93e08d2d450f)

**Comment by DragN0007** [comment]
Weird!
What game and mod version are you on?

**Comment by Rinkavlu** [comment]
1.20.1

**Comment by DragN0007** [comment]
Thank you. I actually see the exact issue. Dumb oversight by me when I was rushing the update out. Sending out a hotfix now

**Comment by Rinkavlu** [comment]
awesome tysm!

**Comment by DragN0007** [comment]
I replaced the old 1.20.1-1.2 verison with the fixed one. Just redownload it and replace the old one and you should be good to go!
