### ISSUE TITLE
Crash with fish of thieves

### ISSUE THREAD

**Issue by alarmgoose** [DragN0007/Overhauled-Livestock#30]
Game crashes when fish of thieves is installed!
[crash-2024-12-25_01.42.49-client.txt](https://github.com/user-attachments/files/18244012/crash-2024-12-25_01.42.49-client.txt)

**Comment by DragN0007** [comment]
Go to their issues and report it to them. I can't fix their mod compatibility, it seems like they're trying to cast my revamped tadpoles to some other renderer and it's causing a crash

**Comment by alarmgoose** [comment]
Okay, thank you.
