### ISSUE TITLE
Game crashes when you try to grow biomes of plenty jacaranda sapling 

### ISSUE THREAD

**Issue by Mooniray** [DragN0007/Overhauled-Livestock#31]
**Bug Description:*
jacaranda saplings are basically ungrowable and will crash your world if you try to grow them the sapling just disappears I removed livestock overhaul and then it worked. bonemealing and growing naturally both have the same effect. not sure if other saplings have the same outcome. vanilla saplings grow, and so does quark's saplings. 

**Mod Version:**
1.20.1
**Minecraft Version:**
1.20.1
**Screenshot (Optional):**

**Have you tried removing other mods? Did the issue persist after removing them?:**
yes, tried removing everything i thought it was, tried on multiple modpacks same issue every time, my boyfriend had the same result on his pc as well 
**Are you on Singleplayer or a Server?:**
singleplayer. issue was discovered on a lan server but even not open to lan in a new world and a different modpack the issue was still there. i figured this was a really important bug to mention since biomes o plenty is a extremely popular mod,
-Before posting an issue, please make sure you’re on the latest version of the mod. There’s a possibility it’s already been fixed!

**Comment by DragN0007** [comment]
What is a jacaranda sapling? What mod is that from? I need more info

**Comment by DragN0007** [comment]
Nvm, it's from BoP. We've gotten this same issue report a couple times before but I have no idea how to fix it. LO doesn't mess with any sort of modded trees so I don't even know why something like that would happen.

You can remove LO safely from your world by following my failsafe instructions,
https://github.com/DragN0007/Overhauled-Livestock/wiki/Safe-Uninstallation

**Comment by DragN0007** [comment]
For those having this issue in the future:

BoP has been now marked as an Incompatibility on the wiki. Use with LO at your own risk.
