### ISSUE TITLE
Cows Constantly Waking into one another 

### ISSUE THREAD

**Issue by Stghe7** [DragN0007/Overhauled-Livestock#33]
**Bug Description:**
Cows are constantly waking into each other

**Mod Version:**
1.20.1-1.7.1
**Minecraft Version:**
1.20.1
**Screenshot (Optional):**

**Have you tried removing other mods? Did the issue persist after removing them?:**
YES
**Are you on Singleplayer or a Server?:**
Singleplayer
-Before posting an issue, please make sure you’re on the latest version of the mod. There’s a possibility it’s already been fixed!

**Comment by DragN0007** [comment]
This is just due to the herding mechanic. You can turn it off in the config
