### ISSUE TITLE
Animals are all constantly walking into one another. 

### ISSUE THREAD

**Issue by Stghe7** [DragN0007/Overhauled-Livestock#34]
**Bug Description:**
All the animals within any pens that i have are all constantly walking into one another. I got your message, and i changed the config.
 From animals herding  “true” to animals herding “false”
This is no longer happening with just the cows. The cows, sheep, pigs, chickens are all doing it. 

**Mod Version:**
1.8 and 1.7.1
**Minecraft Version:**
1.20.1
**Screenshot (Optional):**
![IMG_0306](https://github.com/user-attachments/assets/bb6a39f0-6cba-418f-b35d-3fee3e54c441)

**Have you tried removing other mods? Did the issue persist after removing them?:**
yes
**Are you on Singleplayer or a Server?:**
single player

-Before posting an issue, please make sure you’re on the latest version of the mod. There’s a possibility it’s already been fixed!

**Comment by DragN0007** [comment]
Only thing I can suggest is making your pen bigger. Vanilla animals often do this as well.
