### ISSUE TITLE
Hundreds of animals

### ISSUE THREAD

**Issue by William6020** [DragN0007/Overhauled-Livestock#4]
Hi I'm playing on 1.20.1 and have the "respawning animals" mod on, when enabled this causes hundreds of O-animals to spawn throughout the world and not properly despawn.

My world is flooded with animals, it's an easy fix on my end but I thought I should report it anyway : D

**Comment by DragN0007** [comment]
Hey!

Yeah, sorry I had the same issue with that mod. Unfortunately I don't recommend using it with this or vice versa... I'm unsure if they'd be able to fix that on their end or what. Sorry!
