### ISSUE TITLE
Thousands of bees spawn from one bee nest

### ISSUE THREAD

**Issue by lostmelodies** [DragN0007/Overhauled-Livestock#5]
Heya! So I just started using this mod on a server and after growing a tree with a bee hive attached, bees started spawning by the thousands, causing immense lag. The only way to get rid of them was by killing all bees through commands. Unfortunately, they just immediately spawned back in after this, meaning the only way to actually fix the issue was to destroy the nest altogether.

I'm playing in 1.20.1 on an Exaroton-run server.

**Comment by DragN0007** [comment]
Agh, that's so annoying! I could've sworn we had fixed that bug; but I guess we only fixed it for pre-spawned nests. 

So sorry for the inconvenience, I'll look into it and try to fix it ASAP.

**Comment by lostmelodies** [comment]
I figured it was an issue related to new nests as I hadn't noticed them spawning like this from chunks that I'd already visited. It was certainly a funny bug to have found though haha. Thank you for your quick response ^-^
