### ISSUE TITLE
Pig killing

### ISSUE THREAD

**Issue by lside101** [DragN0007/Overhauled-Livestock#6]
Hii, so whenever I make a compost farm, a pig spawns in that farm and dies. The farm is basically one barrel, one hopper on top, then one composter, then another hopper, and then another barrel on top of that hopper. The mod has been very interesting to play with by the way! Thank you for the mod!

**Comment by DragN0007** [comment]
Oh that's... so weird LOL
I'll take a look at that

**Comment by DragN0007** [comment]
I tried this out and got no pig or anything weird. I can only assume that maybe it's an ID mixup from having lots of mods on, or maybe something else unrelated to Livestock Overhaul ^-^
