### ISSUE TITLE
Mule issues (broken spawn eggs and gender test crashes) + Missing Gender Marker

### ISSUE THREAD

**Issue by SarahMJacobs** [DragN0007/Overhauled-Livestock#7]
Version 1.20.1-1.3, with no other mods installed (except GeckoLib). I did not touch the config file.

### Summary:
- Using a gender test strip on a mule crashes the game.
- O-Mule Spawn Eggs do not function.
- Blue or pink dot does not show up in equine GUIs.

**Gender Test Crash:**
I bred my horse & donkey to create a mule, then tried to use a gender test strip on the mule, and the game immediately froze and crashed. I tried it again and it crashed a second time. Both times, my saves were unaffected and I did not lose any progress. 

_Error message when gender testing mule:_

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.network.syncher.SynchedEntityData$DataItem.m_135403_()" because the return value of "net.minecraft.network.syncher.SynchedEntityData.m_135379_(net.minecraft.network.syncher.EntityDataAccessor)" is null

**O-Mule Spawn Eggs:**
I tried to see if the crash also happens with mules from the O-Mule spawn eggs, but the O-mule eggs don't do anything. Regular mule spawn eggs still work, and give the cool modded mules. 

**Missing Gender Marker:**
Also, the dot to indicate a horse or donkey's gender is absent from their GUIs. I can still see their inventory, but with no colored dot. I have not tested this with camels.

**Comment by DragN0007** [comment]
These should all be fixed in 1.4, hopefully within the next couple of days!

**Comment by SarahMJacobs** [comment]
Awesome, thanks for letting me know! I have discovered one more thing: right-clicking on a mule with a carpet in your hand also crashes the game.
