### ISSUE TITLE
Mob spawns

### ISSUE THREAD

**Issue by Mittens365** [DragN0007/Overhauled-Livestock#8]
O-chickens and O-horses keep spawning in caves, no other animals do that and I don't know why.

**Comment by DragN0007** [comment]
I can't seem to replicate this issue. 
Try removing all your mods and adding them back in one by one to see which one is the issue

**Comment by Mittens365** [comment]
i'm sure it's nothing serious, I have like half a dozon Isle of Berk addons
so I'm sure it's one of those messing with it, thanks anyway
