### ISSUE TITLE
wandering trader llamas follow each other

### ISSUE THREAD

**Issue by fridaisy** [DragN0007/Overhauled-Livestock#9]
**Bug Description:**
a wandering trader spawned into my world, nothing crazy. i didnt see him spawn in so idk what happened, but the llamas werent on leads, there were no leads on the ground (could've despawned, i was busy building when they spawned)
but one llama was walking fine, but the other was following it religiously close, as if it was a llama caravan, but the 'lead' llama was not on a lead, so theres no reason for the other llama to be following it

i will mention i havent tried leading them to try to fix the issue, i dont have slimeballs so :(

**Mod Version:** 
1.3 + 1.4

**Minecraft Version:** 
1.20.1

**Screenshot (Optional):**
![image_2024-11-20_162735228](https://github.com/user-attachments/assets/252a41fb-8bb8-46ab-bc61-10bc3d48d3e8) (this is after the update, they are still following each other) (they also switched roles, the grey back was originally the lead)
![image_2024-11-20_162853660](https://github.com/user-attachments/assets/2286e245-240e-4273-9499-7624628ab1a3)
they walk so close together like theyre soulbound ToT

**Have you tried removing other mods? Did the issue persist after removing them?:**
no but i just updated the mod to the most recent vers and the issue is still happening

**Are you on Singleplayer or a Server?:**
singleplayer

**Comment by DragN0007** [comment]
Yes,
Llamas naturally herd with eachother, much like cattle or horses or sheep. It's not a bug :)
